name: bim
channels:
  - conda-forge
  - anaconda
  - dlr-sc
  - jmcmurray
dependencies:
  - python=3.7
  - anaconda::scipy
  - conda-forge::pythonocc-core
  - conda-forge::google-cloud-storage
  - conda-forge::shapely
  - conda-forge::bson
  - jmcmurray::json
  - anaconda::pandas
  - anaconda::openpyxl
  - dlr-sc::oce
  - ifcopenshell::ifcopenshell
